name: 'Setup Chamber and Fetch SSM Parameters'
description: |
  This Action sets up Chamber, retrieves AWS SSM parameters, and exports them as environment variables for use in workflows.
author: 'Anudeep Samaiya'
branding:
  icon: 'settings'
  color: 'blue'

inputs:
  parameters:
    description: 'List of SSM parameters with optional custom environment variable mappings (e.g. ["/my-app/db-password:MY_DB_PASSWORD", "/my-app/api-key"]).'
    required: true

  namespaced:
    description: 'If true, includes the namespace in the environment variable name (e.g. MY_APP_DB_PASSWORD). If false, uses only the parameter name (e.g. DB_PASSWORD).'
    required: false
    default: 'true'

  aws-region:
    description: 'The AWS region where your SSM parameters are stored.'
    required: false

  aws-access-key-id:
    description: 'AWS access key ID'
    required: false

  aws-secret-access-key:
    description: 'AWS secret access key'
    required: false
    
  chamber_version:
    description: 'Version of Chamber to install. If not specified, defaults to 2.10.12.'
    required: false
    default: '2.10.12'

runs:
  using: "composite"
  steps:
    - name: Set up AWS CLI with provided or environment credentials
      shell: bash
      run: |
        aws configure set aws_access_key_id "${{ inputs.aws-access-key-id || env.AWS_ACCESS_KEY_ID }}"
        aws configure set aws_secret_access_key "${{ inputs.aws-secret-access-key || env.AWS_SECRET_ACCESS_KEY }}"
        aws configure set region "${{ inputs.aws-region || env.AWS_REGION || 'us-east-1' }}"

    - name: Install Chamber
      shell: bash
      run: |
        CHAMBER_VERSION="${{ inputs.chamber_version || env.CHAMBER_VERSION || '2.10.12' }}"
        
        # Check if Chamber is installed
        if ! command -v chamber &> /dev/null; then
          echo "Chamber not found, installing version $CHAMBER_VERSION..."
          
          # Create a temporary directory for download
          mkdir -p /tmp/chamber
          
          # Handle 'latest' version by getting the latest release tag
          if [[ "$CHAMBER_VERSION" == "latest" ]]; then
            echo "Finding latest Chamber release..."
            RELEASES_URL="https://api.github.com/repos/segmentio/chamber/releases/latest"
            LATEST_TAG=$(curl -s $RELEASES_URL | grep -Po '"tag_name": "\K[^"]*')
            if [[ -n "$LATEST_TAG" ]]; then
              # Remove 'v' prefix if present
              CHAMBER_VERSION=${LATEST_TAG#v}
              echo "Latest Chamber version is $CHAMBER_VERSION"
            else
              echo "Failed to determine latest version, falling back to default 2.10.12"
              CHAMBER_VERSION="2.10.12"
            fi
          fi
          
          # Download Chamber
          DOWNLOAD_URL="https://github.com/segmentio/chamber/releases/download/v${CHAMBER_VERSION}/chamber-v${CHAMBER_VERSION}-linux-amd64"
          echo "Downloading Chamber from $DOWNLOAD_URL"
          curl -sSL "$DOWNLOAD_URL" -o /tmp/chamber/chamber
          chmod +x /tmp/chamber/chamber
          sudo mv /tmp/chamber/chamber /usr/local/bin/chamber
          
          # Verify installation
          echo "Chamber installed:"
          chamber version || echo "Warning: Chamber was installed but version check failed"
        else
          echo "Chamber is already installed:"
          chamber version
        fi

    - name: Fetch and set SSM parameters as env variables
      shell: bash
      run: |
        # Process each parameter from the multi-line input
        echo "${{ inputs.parameters }}" | while IFS= read -r ssm_param_name || [[ -n "$ssm_param_name" ]]; do
          # Skip empty lines
          [[ -z "$ssm_param_name" ]] && continue
          
          param=${ssm_param_name%%:*}  # Extract SSM parameter (before the colon)
          custom_env_var=${ssm_param_name#*:}  # Extract custom env var (after the colon)
          
          # Check if there's a custom env var mapping (contains a colon)
          if [[ "$param" == "$custom_env_var" ]]; then
            custom_env_var=""
          fi

          # Fetch parameter value using Chamber
          echo "Fetching parameter: $param"

          # Split the SSM parameter path into service and key parts for Chamber
          # Remove leading slash if present and get the first part as service name
          service=$(echo "$param" | sed 's/^\///' | cut -d'/' -f1)
          # Get everything after the service name as the key
          key=$(echo "$param" | sed "s/^\/$service\///;s/^$service\///")

          echo "Using Chamber to read service: $service, key: $key"

          # Use Chamber to read parameter
          value=$(chamber read "$service" "$key")

          if [ $? -ne 0 ]; then
            echo "Error: Failed to fetch parameter $param"
            exit 1
          fi

          # Extract the prefix (namespace) from the parameter (first part before the slash)
          prefix=$(echo "$param" | sed 's|^/||' | cut -d'/' -f1 | tr 'a-z' 'A-Z' | tr '-' '_')
          
          # Extract parameter name (last part after the last slash)
          param_name=$(echo "$param" | sed 's|.*/||' | tr 'a-z' 'A-Z' | tr '-' '_')

          # Handle custom logic in shell
          if [[ "${{ inputs.namespaced }}" == "false" && -n "$custom_env_var" ]]; then
            env_name="$custom_env_var"
          elif [[ "${{ inputs.namespaced }}" == "false" ]]; then
            env_name="$param_name"
          else
            env_name="${prefix}_${param_name}"
          fi

          # Export the parameter to the environment
          echo "Setting parameter $param as $env_name"
          echo "$env_name=$value" >> $GITHUB_ENV
        done