version: '3'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ssm
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./test-data:/tmp/localstack/data
      - ./test-scripts:/docker-entrypoint-initaws.d
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  test-runner:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - CHAMBER_AWS_SSM_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack
    command: >
      sh -c "
        apk add --no-cache curl bash aws-cli jq &&
        echo 'Waiting for LocalStack...' &&
        until curl -s http://localstack:4566/health | grep -q '\"ssm\": \"running\"'; do
          echo 'Waiting for SSM service...' &&
          sleep 1;
        done &&
        echo 'Creating test parameters...' &&
        aws --endpoint-url=http://localstack:4566 ssm put-parameter --name '/test-app/db-password' --value 'password123' --type String &&
        aws --endpoint-url=http://localstack:4566 ssm put-parameter --name '/test-app/api-key' --value 'api-key-abc' --type String &&
        echo 'Test parameters created. Ready for testing!'
      "