# Docker Compose configuration for testing with LocalStack

services:
  # LocalStack service
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-test
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ssm
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "/tmp/localstack:/tmp/localstack"
    healthcheck:
      test: "curl -s http://localhost:4566/health?services=ssm | grep -q '\"ssm\": \"running\"' || exit 1"
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 10s

  # Test runner container
  test-runner:
    image: node:18
    depends_on:
      localstack:
        condition: service_healthy
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - CHAMBER_AWS_SSM_ENDPOINT=http://localstack:4566
      - TEST_PARAM_1=/test-action/param1
      - TEST_PARAM_2=/test-action/param2
      - TEST_VALUE_1=value1
      - TEST_VALUE_2=value2
      - DOCKER_ENV=true
    entrypoint: ["tail", "-f", "/dev/null"]