# Docker Compose configuration for testing with LocalStack

services:
  # LocalStack service
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-test
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ssm
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "/tmp/localstack:/tmp/localstack"
    healthcheck:
      test: "curl -s http://localhost:4566/health?services=ssm | grep -q '\"ssm\": \"running\"' || exit 1"
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s