name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  validate:
    name: Validate Action Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: make setup
        
      - name: Validate action.yml
        id: validate
        run: npm run validate
      
      - name: Generate validation summary
        if: always()
        run: |
          echo "## Validation Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Action Config**: ${{ steps.validate.outcome || 'Unknown' }}" >> $GITHUB_STEP_SUMMARY
          
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: make setup
        
      - name: Run linters
        id: lint
        run: npm run lint
      
      - name: Generate lint summary
        if: always()
        run: |
          echo "## Lint Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **ESLint**: ${{ steps.lint.outcome || 'Unknown' }}" >> $GITHUB_STEP_SUMMARY