name: Setup Node.js and Docker

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '18'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
      
      # Setup Docker buildx for better caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # Cache Docker images to speed up workflow runs
      - name: Cache Docker images
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: Install dependencies
        run: npm ci
        
      # Output success message
      - name: Setup complete
        run: |
          echo "Node.js setup complete: $(node --version)"
          echo "npm setup complete: $(npm --version)"
          echo "Docker setup complete: $(docker --version)"