name: Test Summary

on:
  workflow_run:
    workflows:
      - Code Quality
      - Functional Tests
    types:
      - completed

jobs:
  summary:
    name: Test Summary
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}
    steps:
      - name: Generate test report
        run: |
          echo "## GitHub Action Tests Summary" >> $GITHUB_STEP_SUMMARY
          echo "### Workflow Results" >> $GITHUB_STEP_SUMMARY
          
          # Workflow name and result from the triggering event
          echo "- **${{ github.event.workflow_run.name }}**: ${{ github.event.workflow_run.conclusion }}" >> $GITHUB_STEP_SUMMARY
          
          # Link to the workflow run
          echo "  [View Details](https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }})" >> $GITHUB_STEP_SUMMARY