name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: make setup
        
      - name: Run unit tests
        id: unit_tests
        run: npm run test:unit
      
      - name: Upload test coverage
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-coverage
          path: coverage/
          retention-days: 5
      
      - name: Generate test summary
        if: always()
        run: |
          echo "## Unit Tests Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Unit Tests**: ${{ steps.unit_tests.outcome || 'Unknown' }}" >> $GITHUB_STEP_SUMMARY