name: Usage Example

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS Region for SSM parameters'
        required: false
        default: 'us-east-1'
      namespaced:
        description: 'Use namespaced environment variables'
        required: false
        default: 'true'
        type: string
      chamber_version:
        description: 'Chamber version to use'
        required: false
        default: '2.10.12'
        type: string

jobs:
  example-usage:
    name: Example Usage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region || 'us-east-1' }}

      # Use the Chamber AWS SSM Parameter Store action
      - name: Fetch SSM Parameters
        uses: anudeepsamaiya/chamber-aws-ssm-parameter-store@main
        with:
          parameters: |
            /my-app/api/database-url
            /my-app/api/api-key
            /my-app/api/client-secret:CLIENT_SECRET
          namespaced: ${{ github.event.inputs.namespaced || 'true' }}
          chamber_version: ${{ github.event.inputs.chamber_version || '2.10.12' }}

      # Example of how to use the parameters
      - name: Use the parameters in your workflow
        run: |
          echo "Example of how to use the fetched parameters:"
          
          # Access parameters using environment variables
          if [ "${{ github.event.inputs.namespaced || 'true' }}" = "true" ]; then
            echo "echo \$MY_APP_DATABASE_URL  # Database URL"
            echo "echo \$MY_APP_API_KEY       # API key"
          else
            echo "echo \$DATABASE_URL        # Database URL"
            echo "echo \$API_KEY             # API key"
          fi
          
          # Custom parameter name (works with both namespaced and non-namespaced)
          echo "echo \$CLIENT_SECRET        # Client secret"
          
          echo -e "\nExample of using parameters in deployment:"
          echo "---------------------------------------------"
          echo "docker run -e DB_URL=\$MY_APP_DATABASE_URL -e API_KEY=\$MY_APP_API_KEY my-image"