name: Use Chamber to Fetch SSM Secrets

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Chamber and Fetch Parameters
        uses: my-org/chamber-setup-action@v1
        with:
          aws-region: 'us-east-1'
          parameters: '/my-app/db-password,/my-app/api-key'
          with-decryption: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Use the fetched secrets
        run: |
          echo "DB Password is $MY_APP_DB_PASSWORD"
          echo "API Key is $MY_APP_API_KEY"
