name: Example - Fetch SSM Parameters

# This workflow is provided as an example for users of this action

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy-with-ssm-params:
    name: Deploy with SSM Parameters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Example showing how to use the GitHub Action
      - name: Fetch SSM Parameters
        uses: anudeepsamaiya/chamber-aws-ssm-parameter-store@main
        with:
          parameters:
            - "/my-app/api/database-url"
            - "/my-app/api/api-key"
            - "/my-app/api/client-secret:CLIENT_SECRET" # Custom mapping
          namespaced: 'true'  # Will create MY_APP_DATABASE_URL, MY_APP_API_KEY, CLIENT_SECRET
       
      # Example of using the imported parameters in a subsequent step
      - name: Deploy application
        run: |
          echo "Deploying application with the following parameters:"
          echo "Database URL: $MY_APP_DATABASE_URL"
          echo "API Key: $MY_APP_API_KEY"
          echo "Client Secret: $CLIENT_SECRET"
          
          # Example deployment commands using the params
          # npm run deploy -- --db-url=$MY_APP_DATABASE_URL --api-key=$MY_APP_API_KEY
          
          # Example Docker commands
          # docker run -e DB_URL=$MY_APP_DATABASE_URL -e API_KEY=$MY_APP_API_KEY my-docker-image:latest